### ISSUE TITLE
Unexpected Markdown behavior

### ISSUE THREAD

**Issue by stcz** [advanced-chat/vue-advanced-chat#409]
## Describe the bug

If I write a markdown text, where I use a `~`, `*`, `_`... in two different lines a part of the text will be removed.

````
Write a * somewhere.
And later another * in a new line.
````
The Text will be modified as follows:
```
Write a And later another er another * in a new line.
```
The problem seems to be the combination with the new line

## Steps to reproduce

 1. Go to 'https://antoine92190.github.io/vue-advanced-chat/'
 2. Click on a chat
 3. Paste 
 ```
Write a * somewhere.
And later another * in a new line.
 ```
 5. See error

## Expected behavior

The Text should not be modified.

Expected either no change:

Write a * somewhere.
And later another * in a new line.

Or expected a bold text over a line:

Write a  **somewhere.**
**And later another**  in a new line.

## Screenshots
![grafik](https://user-images.githubusercontent.com/66465573/206395632-e34b0829-f07c-4c7f-b8de-f57e4734c003.png)

## Device 

- OS: Ubuntu 22.04
- Browser: Firefox 107
- Package version: 2.0.6

**Comment by antoine92190** [comment]
Thanks for opening this issue, indeed it's a bug I can reproduce

**Comment by changye0413** [comment]
When I input "import [java.io](http://java.io/).U" or other similar links, it will be fragmented.
<img width="140" alt="截屏2023-03-10 00 28 06" src="https://user-images.githubusercontent.com/50126154/224090094-6bf05371-c4d0-44e5-bf53-1c1d4ea49cbd.png">

**Comment by changye0413** [comment]
When Python or other code that requires indentation is displayed in a multilineCode block, spaces are omitted and replaced with one space. It would be helpful to add a configuration to prevent this, so that the server does not need to perform the conversion. Thank you.
