### ISSUE TITLE
Can you please document how to limit upload to a single file?

### ISSUE THREAD

**Issue by Premke** [advanced-chat/vue-advanced-chat#458]
## Is your feature request related to a problem? Please describe

No, to a client request - client wants to upload a single file.

## Describe the solution you'd like

A prop on `<vue-advanced-chat use-single-file />`.

## Describe alternatives you've considered

Search for another issue https://github.com/antoine92190/vue-advanced-chat/issues/321 - however its closed without elaboration...

## Additional context

None.

**Comment by fabioselau077** [comment]
Fork and remove this line "multiple"
https://github.com/antoine92190/vue-advanced-chat/blob/7a30bd54d6175c21695de6fd5298ba53773c37dd/src/lib/Room/RoomFooter/RoomFooter.vue#L164

**Comment by Premke** [comment]
Thanks, will try it out.
