### ISSUE TITLE
room without message

### ISSUE THREAD

**Issue by mateus3690** [advanced-chat/vue-advanced-chat#483]
When the room has no message, it keeps loading a spinner animation. How do I disable this, and how do I change the default language?

**Comment by aerovulpe** [comment]
Hey @mateus3690,

`loadingMessages` controls the room message loader.

Also you can override the UI language by setting a custom `textMessages` object. You can find the schema for `textMessages` here https://github.com/advanced-chat/vue-advanced-chat/blob/master/src/locales/index.js
