### ISSUE TITLE
URGENT ** 2.0.8 NPMJS Package Missing Files | Broken

### ISSUE THREAD

**Issue by palmtown** [advanced-chat/vue-advanced-chat#489]
## Describe the bug

The latest npmjs package is missing all the required files and is now broken when installing.  Please fix.

## Steps to reproduce

Install vue-advanced-chat 2.0.8

## Expected behavior

vue-advanced-chat installs with all necessary files

## Screenshots

![image](https://github.com/advanced-chat/vue-advanced-chat/assets/4324865/320ff9d6-cd58-4577-aca3-9d4768040f91)

**Comment by aerovulpe** [comment]
Hey @palmtown, thank you for alerting us to this.

We've published a new version `2.0.9` that includes the missing files.

**Comment by palmtown** [comment]
Hello @aerovulpe,

Thanks for your prompt response, much appreciated and I'm grateful for the excellent work!
