### ISSUE TITLE
Named Slots not working with vue 3

### ISSUE THREAD

**Issue by julianodev** [advanced-chat/vue-advanced-chat#512]
I'm trying to use named slots but it doesn't render anything.

 <template #room-header="{ room, userStatus }">
                {{ room.roomName }} - {{ userStatus }}
            </template>

But if I use 

<div slot="room-header"></div>

It works perfectly

Any idea what it could be?

**Comment by vesper8** [comment]
Same here. I get this rather unhelpful message `[vite] Internal server error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.` when I try to use the new slot syntax
