### ISSUE TITLE
Positioning Issue with .vac-room-header in vue-advanced-chat

### ISSUE THREAD

**Issue by thierbig** [advanced-chat/vue-advanced-chat#523]
## Describe the bug
When using `vue-advanced-chat`, the `.vac-room-header` is styled with `position: absolute;`, which interferes with the actual header in my application, causing layout issues.

## Steps to reproduce
To help reproduce the issue, you can use the sandbox environment provided at https://github.com/advanced-chat/vue-advanced-chat-sandbox. Here are the steps:

1. Set up a basic instance of `vue-advanced-chat`.
2. Add a static header above the chat component in your application layout.
3. Initialize the chat component with default settings.
4. Observe that the `.vac-room-header` overlaps or incorrectly positions itself relative to the static page header.

## Expected behavior
I expect that the `.vac-room-header` should not interfere with other elements outside of the chat component. Changing the CSS position property of `.vac-room-header` from `absolute` to `fixed` should resolve this issue, ensuring that it stays positioned correctly without affecting the layout of other page elements.

## Screenshots
If applicable, add screenshots to help explain the problem. [Add screenshots here]

## Device (please complete the following information)
- OS: [e.g., iOS, Windows 10]
- Browser: [e.g., Chrome 90, Safari 14]
- Package version: [e.g., 0.5.1]

## Additional context
This styling issue may affect users who have other fixed or absolute elements in their applications. Adjusting the CSS directly within the component may help resolve this without forcing users to apply override styles externally.

**Comment by aerovulpe** [comment]
Hey @thierbig, thanks for opening this issue!

I merged your [pull request](https://github.com/advanced-chat/vue-advanced-chat/pull/524). However, `position: fixed`  also has issues.

It makes the room header width `100%` of the viewport, overextending the element in some instances (including the [project demo](https://advanced-chat.github.io/vue-advanced-chat/))

<img width="1435" alt="image" src="https://github.com/advanced-chat/vue-advanced-chat/assets/6438457/d6d675f8-5b4b-421b-9890-232d696ea23e">

I think `position: sticky` might be a better solution. Can you try this with your project? If that works, create a follow-up pull request, and I can get that merged if it passes the demo virtual test.

**Comment by thierbig** [comment]
@aerovulpe 

`position: sticky` is also problematic. The default will revert back to `absolute` :)

I went ahead and added parameters to fix the header styles instead: https://github.com/advanced-chat/vue-advanced-chat/pull/525

**Comment by aerovulpe** [comment]
Yeah, I like this solution better!

**Comment by aerovulpe** [comment]
@thierbig, version [2.1.0](https://github.com/advanced-chat/vue-advanced-chat/releases/tag/2.1.0) has been released, incorporating your changes.

Thanks for your contributions!

**Comment by thierbig** [comment]
<3
